######################################################################
# Automatically generated by qmake (2.01a) mar. nov. 8 16:20:07 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.hh
SOURCES += main.cpp window.cpp
RESOURCES += qml.qrc
